# Generated by Django 2.2.10 on 2020-02-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lux_tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.CharField(default='image.png', max_length=200),
        ),
    ]
