# Generated by Django 2.2.10 on 2020-03-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lux_tienda', '0004_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='articulo',
            field=models.CharField(default='/', max_length=200),
        ),
    ]
